services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    ports:
      - "9200:9200"
    environment:
      - ES_JAVA_OPTS=-Xmx1024m -Xms1024m
      - discovery.type=single-node
      - xpack.security.enabled=false
    stdin_open: true
    tty: true

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200