name: Test

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
          pip install coverage-badge
      - name: Test with pytest
        run: |
          pytest --cov .
      - name: Generate coverage badge
        run: |
          coverage-badge -o coverage.svg
      - name: Commit and push if changed
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add coverage.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update coverage badge"
          git push